name: ThumbnailTest

options:
  bundleIdPrefix: com.thumbnailtest
  deploymentTarget:
    iOS: "16.0"

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  ThumbnailTest:
    type: application
    platform: iOS
    sources:
      - ThumbnailTest
    info:
      path: ThumbnailTest/Info.plist
      properties:
        CFBundleDisplayName: ThumbnailTest
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSPhotoLibraryUsageDescription: "We need access to your photo library to let you select thumbnails for analysis."
        NSCameraUsageDescription: "We need access to your camera to let you take photos of thumbnails for analysis."
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.thumbnailtest.app
      INFOPLIST_FILE: ThumbnailTest/Info.plist
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      TARGETED_DEVICE_FAMILY: "1,2"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_PREVIEWS: true
    dependencies:
      - framework: StoreKit.framework
      - framework: SwiftUI.framework
      - framework: Combine.framework
      - framework: PhotosUI.framework
